### ISSUE TITLE
Suggestion: Create an installation guide for Windows and Mac users

### ISSUE THREAD

**Issue by Saharsh0028** [ArcadiaLinux/Arcadia#2]
Hi! I'd really like to download the ArcadiaLinux iso onto a bootable usb, but as far as I can tell, `./build.sh` works only on Linux distros.
Would it be possible to create an installation guide for Windows and MacOS users to install the iso?

**Comment by gaganmalvi** [comment]
build.sh is the script used to compile the ISO image that works only on Arch Linux based environments. 
ISO images will be updated shortly.
